//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarracaDeFeira.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdBarracaDeFeiraEntities : DbContext
    {
        public BdBarracaDeFeiraEntities()
            : base("name=BdBarracaDeFeiraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entrada> Entrada { get; set; }
        public DbSet<Estoque> Estoque { get; set; }
        public DbSet<Pedido> Pedido { get; set; }
        public DbSet<PedidoProduto> PedidoProduto { get; set; }
        public DbSet<Pessoa2> Pessoa2 { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<Setor> Setor { get; set; }
    }
}
