//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarracaDeFeira.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Entrada = new HashSet<Entrada>();
            this.Estoque = new HashSet<Estoque>();
            this.PedidoProduto = new HashSet<PedidoProduto>();
        }
    
        public int idProduto { get; set; }
        public string descricaoProduto { get; set; }
        public decimal valorUnitario { get; set; }
    
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<Estoque> Estoque { get; set; }
        public virtual ICollection<PedidoProduto> PedidoProduto { get; set; }
    }
}
